server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:8080/rental_management
    username: postgres
    password: pgadmin
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

      # configuration du chemin de base pour swagger
springdoc:
  swagger-ui:
    path: /swagger
